/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.PedidosDAO;
import VO.PedidosVO;
import java.text.DateFormat;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wilson
 */
public class Reporte1 extends javax.swing.JDialog {

    public static DefaultTableModel modeloreporte1;
    private PedidosDAO pedidos = new PedidosDAO();

    /**
     * Creates new form Reporte1
     */
    public Reporte1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String pilas[][] = {};
        String columnas[] = {"Id_Pedido", "Id_Mesa", "Id_Plato", "Cedula Del Mesero", "Fecha", "Estado", "Hora"};
        jTable1.setOpaque(false);
        ((DefaultTableCellRenderer) jTable1.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);
        jTable1.setShowGrid(false);
        modeloreporte1 = new DefaultTableModel(pilas, columnas);
        jTable1.setModel(modeloreporte1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        f1 = new com.toedter.calendar.JDateChooser();
        f2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cantidad De Pedidos Por Rango de Fecha");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));
        getContentPane().add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jButton1.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/info.png"))); // NOI18N
        jButton1.setText("Procesar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(java.awt.Color.orange);
        jTable1.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 255));
        jTable1.setSelectionBackground(new java.awt.Color(0, 255, 51));
        jTable1.setSelectionForeground(new java.awt.Color(0, 255, 51));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 190, 540, 90));

        jLabel1.setBackground(java.awt.Color.orange);
        jLabel1.setFont(new java.awt.Font("Calibri Light", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cantidad de pedidos en total: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 120, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/luxx-madrid-2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int contador = 0;
        if (f1.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la 1° Fecha de rango");

        } else if (f2.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la 2° Fecha de rango");

        } else {
            LinkedList listapedidos = pedidos.listarPedidos();
            for (int i = 0; i < listapedidos.size(); i++) {
                PedidosVO pedido = (PedidosVO) listapedidos.get(i);
                long a = f2.getDate().getTime();
                long b = f1.getDate().getTime();
                if (pedido.getFecha().getTime() >= b && pedido.getFecha().getTime() <= a) {

                    for (int y = modeloreporte1.getRowCount() - 1; y >= 0; y--) {
                        modeloreporte1.removeRow(y);
                    }
                    for (int h = 0; h < listapedidos.size(); h++) {
                        PedidosVO p1 = (PedidosVO) listapedidos.get(h);
                        modeloreporte1.insertRow(h, new Object[]{});
                        modeloreporte1.setValueAt(p1.getId_pedido(), h, 0);
                        modeloreporte1.setValueAt(p1.getId_mesa(), h, 1);
                        modeloreporte1.setValueAt(p1.getId_plato(), h, 2);
                        modeloreporte1.setValueAt(p1.getCedula_mesero(), h, 3);
                        DateFormat formato1 = DateFormat.getDateInstance();
                        String sfecha = formato1.format(p1.getFecha());
                        modeloreporte1.setValueAt(sfecha, h, 4);
                        //       modeloreporte1.setValueAt(p1.getFecha(), h, 4);
                        modeloreporte1.setValueAt(p1.getEstado_pedido(), h, 5);
                        modeloreporte1.setValueAt(p1.getHora_pedido(), h, 6);
                    }
                    contador++;
                }

            }
            jTextField1.setText(String.valueOf(contador));
            contador = 0;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporte1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporte1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporte1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporte1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Reporte1 dialog = new Reporte1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser f1;
    private com.toedter.calendar.JDateChooser f2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
